version: 2

project_name: go-mitmproxy

builds:
  - binary: go-mitmproxy
    main: ./cmd/go-mitmproxy/
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/denisvmedia/go-mitmproxy/version.Version={{.Version}} -X github.com/denisvmedia/go-mitmproxy/version.Commit={{.ShortCommit}} -X github.com/denisvmedia/go-mitmproxy/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - '386'
    goarm:
      - '6'
      - '7'
    ignore:
      - goos: darwin
        goarch: '386'
      # Deprecated in go1.25, Removed in go1.26
      # https://go.dev/doc/go1.25#windows
      - goos: windows
        goarch: arm

archives:
  - formats: [ 'tar.gz' ]
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

snapshot:
  version_template: SNAPSHOT-{{ .Commit }}

checksum:
  disable: false
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '(?i)^docs?:'
      - '(?i)^docs\([^:]+\):'
      - '(?i)^docs\[[^:]+\]:'
      - '^tests?:'
      - '(?i)^dev:'
      - '(?i)^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: denisvmedia
    name: go-mitmproxy
  header: |
    ## go-mitmproxy {{ .Version }}
    
    `go-mitmproxy` is a Golang implementation of [mitmproxy](https://mitmproxy.org/) that supports man-in-the-middle attacks and parsing, monitoring, and tampering with HTTP/HTTPS traffic.
    
    ### Installation
    
    ```bash
    go install github.com/denisvmedia/go-mitmproxy/cmd/go-mitmproxy@{{ .Tag }}
    ```

source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}-source'

